name: ChangeLog

on:
  push:
    branches:
      - main

jobs:
  build:
    steps:
    - name: Change Log
      uses: mikepenz/release-changelog-builder-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
