name: Coverage

on:
  pull_request:

env:
  GITHUB_ACTIONS: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby Head
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: head
        bundler-cache: true
    - name: RSpec
      run: bundle exec rake spec
    - name: Report Coverage
      uses: romeovs/lcov-reporter-action@v0.2.16
      with:
        lcov-file: ./coverage/lcov/ruby-simplecov.lcov
        github-token: ${{ secrets.GITHUB_TOKEN }}
