name: Ruby

on:
  push:
    branches:
      - main
  pull_request:

env:
  GITHUB_ACTIONS: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '2.7'
          - '3.0'
          - '3.1'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Rake Spec
      run: bundle exec rake spec
    - name: Report Coverage
      uses: romeovs/lcov-reporter-action@v0.2.16
      with:
        lcov-file: ./coverage/lcov/ruby-simplecov.lcov
        github-token: ${{ secrets.GITHUB_TOKEN }}
